# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messages_pb2 as messages__pb2


class IdentifeyeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendData = channel.unary_unary(
        '/identifeye.IdentifeyeService/SendData',
        request_serializer=messages__pb2.DataPoint.SerializeToString,
        response_deserializer=messages__pb2.Response.FromString,
        )
    self.SendDataBulk = channel.unary_unary(
        '/identifeye.IdentifeyeService/SendDataBulk',
        request_serializer=messages__pb2.BulkData.SerializeToString,
        response_deserializer=messages__pb2.Response.FromString,
        )


class IdentifeyeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendDataBulk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IdentifeyeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendData': grpc.unary_unary_rpc_method_handler(
          servicer.SendData,
          request_deserializer=messages__pb2.DataPoint.FromString,
          response_serializer=messages__pb2.Response.SerializeToString,
      ),
      'SendDataBulk': grpc.unary_unary_rpc_method_handler(
          servicer.SendDataBulk,
          request_deserializer=messages__pb2.BulkData.FromString,
          response_serializer=messages__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'identifeye.IdentifeyeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
