# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='identifeye',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emessages.proto\x12\nidentifeye\"\x9a\x01\n\tDataPoint\x12\x19\n\x11\x61\x63\x63ount_name_hash\x18\x01 \x01(\t\x12\x1b\n\x13\x63haracter_name_hash\x18\x02 \x01(\t\x12\x0f\n\x07ip_hash\x18\x03 \x01(\t\x12\x18\n\x10ip_location_hash\x18\x04 \x01(\t\x12\x11\n\tis_banned\x18\x05 \x01(\x08\x12\x17\n\x0f\x61\x63tive_playtime\x18\x06 \x01(\x05\"/\n\x08\x42ulkData\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.identifeye.DataPoint\"\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x88\x01\n\x11IdentifeyeService\x12\x37\n\x08SendData\x12\x15.identifeye.DataPoint\x1a\x14.identifeye.Response\x12:\n\x0cSendDataBulk\x12\x14.identifeye.BulkData\x1a\x14.identifeye.Responseb\x06proto3')
)




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='identifeye.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name_hash', full_name='identifeye.DataPoint.account_name_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character_name_hash', full_name='identifeye.DataPoint.character_name_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_hash', full_name='identifeye.DataPoint.ip_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_location_hash', full_name='identifeye.DataPoint.ip_location_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_banned', full_name='identifeye.DataPoint.is_banned', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_playtime', full_name='identifeye.DataPoint.active_playtime', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=185,
)


_BULKDATA = _descriptor.Descriptor(
  name='BulkData',
  full_name='identifeye.BulkData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='identifeye.BulkData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=234,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='identifeye.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='identifeye.Response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=263,
)

_BULKDATA.fields_by_name['data'].message_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['BulkData'] = _BULKDATA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:identifeye.DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)

BulkData = _reflection.GeneratedProtocolMessageType('BulkData', (_message.Message,), dict(
  DESCRIPTOR = _BULKDATA,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:identifeye.BulkData)
  ))
_sym_db.RegisterMessage(BulkData)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:identifeye.Response)
  ))
_sym_db.RegisterMessage(Response)



_IDENTIFEYESERVICE = _descriptor.ServiceDescriptor(
  name='IdentifeyeService',
  full_name='identifeye.IdentifeyeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=266,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='identifeye.IdentifeyeService.SendData',
    index=0,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendDataBulk',
    full_name='identifeye.IdentifeyeService.SendDataBulk',
    index=1,
    containing_service=None,
    input_type=_BULKDATA,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IDENTIFEYESERVICE)

DESCRIPTOR.services_by_name['IdentifeyeService'] = _IDENTIFEYESERVICE

# @@protoc_insertion_point(module_scope)
